# standard jekyll configuration
# test

permalink: /articles/:title
pygments: true
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: rdiscount
